In [ ]:
# 배열의 연산과 변형
import numpy as np

# 배열 생성
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [ ]:
## 벡터화 연산(Vectorized Operations)
arr + 2

array([3, 4, 5, 6])

In [3]:
arr * 2

array([2, 4, 6, 8])

In [4]:
# 리스트
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [5]:
list + 2

TypeError: can only concatenate list (not "int") to list

In [ ]:
# 반복
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [13]:
arr = np.arange(1, 5)
arr1 = np.arange(5, 9)
print(arr)
print(arr1)

[1 2 3 4]
[5 6 7 8]


In [14]:
arr + arr1

array([ 6,  8, 10, 12])

In [15]:
arr * arr1

array([ 5, 12, 21, 32])

In [16]:
list = [1, 2, 3, 4]
list1 = [5, 6, 7, 8]

In [17]:
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]