In [1]:
# 배열의 연산과 변형
import numpy as np

# 배열 생성
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [2]:
## 벡터화 연산(Vectorized Operations)
arr + 2

array([3, 4, 5, 6])

In [3]:
arr * 2

array([2, 4, 6, 8])

In [4]:
# 리스트
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [5]:
list + 2

TypeError: can only concatenate list (not "int") to list

In [ ]:
# 반복
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [12]:
arr = np.arange(1, 5)
arr1 = np.arange(5, 9)
print(arr)
print(arr1)

[1 2 3 4]
[5 6 7 8]


In [ ]:
arr + arr1

array([ 6,  8, 10, 12])

In [ ]:
arr * arr1

array([ 5, 12, 21, 32])

In [ ]:
list = [1, 2, 3, 4]
list1 = [5, 6, 7, 8]

In [ ]:
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

## 주요 산술 연산 함수
### 1. 수학 함수들

In [9]:
# 배열 생성
# arr = array([1, 2, 3, 4])

# 제곱
print(np.square(arr))

# 제곱근(루트)
print(np.sqrt(arr))

# exp(지수승)
print(np.exp(arr))

# log(로그)
print(np.log(arr))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


### 2. 배열 연산 함수들

In [18]:
# 더하기
print(np.add(arr, arr1))
print(arr + arr1)

# 합계
print(np.sum(arr))

# 누적합(cumulative + sum)
print(np.cumsum(arr))

[ 6  8 10 12]
[ 6  8 10 12]
10
[ 1  3  6 10]


### 3. 통계 함수들

In [23]:
# 평균
'''
(1 + 2 + 3 + 4)/4 -> 2.5
'''
print(np.mean(arr))
# 분산(variance)
'''
평균: 2.5
편차: -1.5, -0.5, 0.5, 1.5
편차의 제곱: 2.25, 0.25, 0.25, 2.25
분산: (2.25+0.25+0.25+2.25)/4 -> 1.25
'''
print(np.var(arr))
# 표준편차(Standard Deviation)
# 표준편차 -> 분산의 제곱근: 루트1.25 -> 1.118033988749895
print(np.std(arr))

# 최솟값
print(np.min(arr))

# 최댓값
print(np.max(arr))

# 최솟값의 인덱스
print(np.argmin(arr))

# 최댓값의 인덱스
print(np.argmax(arr))

2.5
1.25
1.118033988749895
1
4
0
3


## 배열의 변형(Transformation)
### 1. 축 변환: 배열.transpose()

In [ ]:
# 2차원 배열 생성
arr = np.arange(10).reshape(2, 5)
print(arr)

# 2차원 배열의 축 변환
# (2, 5) -> (5, 2)
print(arr.transpose())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
