# ipynb 단축키
## 편집 모드(코드 작성 모드)
- Shift + Enter: 실행
- Ctrl + Enter: 실행 후 유지
- Alt + Enter: 실행 후 다음 셀 생성
## 명령 모드(esc)
- a: 위에 셀 추가
- b: 아래에 셀 추가
- dd: 셀 삭제
- esc: 셀 선택 해제
- m: 셀 타입 변경 (코드 -> Markdown)
- y: 셀 타입 변경 (Markdown -> 코드)
- z: 실행 취소
- x: 잘라내기
- c: 복사
- v: 붙여넣기

# 라이브러리 설치
## 터미널: pip install numpy
## 셀: %pip install numpy
# 라이브러리 제거
## 터미널: pip uninstall numpy
## 셀: %pip uninstall numpy
# 실행
## py: F5 (사용자가 등록)
## ipynb: Shift + Enter

In [5]:
# 외부 라이브러리(numpy) 설치
%pip install numpy

  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
# 외부 라이브러리(numpy) 제거
%pip uninstall numpy -y

Found existing installation: numpy 2.4.6
Uninstalling numpy-2.4.6:
  Successfully uninstalled numpy-2.4.6
Note: you may need to restart the kernel to use updated packages.


In [6]:
# 외부 라이브러리는 설치후 import 해야 한다.
import numpy as np

In [ ]:
# 참고
# *는 모든 것
from numpy import *

In [8]:
# 리스트의 항목에 2를 곱하기
# 예) [1, 2, 3, 4] -> [2, 4, 6, 8]
# 리스트 연산 -> 반복문 필요!
list_data = [1, 2, 3, 4]
result_list = []
for item in list_data:
    result_list.append(item * 2)
print(result_list)
result_list

[2, 4, 6, 8]


[2, 4, 6, 8]

In [12]:
# 배열 연산 -> 반복문 불필요!
# 벡터화 연산
array_data = np.array([1, 2, 3, 4])
result_array = array_data * 2
print(result_array)
result_array

[2 4 6 8]


array([2, 4, 6, 8])

In [13]:
# 리스트 vs 배열 성능 비교
import time

In [25]:
# 리스트를 사용한 연산
start_time = time.time()
# 1970-01-01 00:00:00 기준으로 초 단위로 시간을 표현한 것
print(start_time)
# [0, 1, 2, 3, ... , 999999] 형태의 리스트 생성
python_list = list(range(1000000))
result_list = [x * 2 for x in python_list]
# print(result_list)
list_time = time.time() - start_time
print(f'리스트 연산 시간: {list_time:.4f}초')

1782356120.382236
리스트 연산 시간: 0.1151초


In [27]:
# NumPy 배열을 사용한 연산
start_time = time.time()
print(start_time)
numpy_array = np.arange(1000000)
result_array = numpy_array * 2
print(result_array)
numpy_time = time.time() - start_time
print(f'NumPy 연산 시간: {numpy_time:.4f}초')
print(f'속도 개선: {list_time/numpy_time:.1f}배')

1782356175.9645286
[      0       2       4 ... 1999994 1999996 1999998]
NumPy 연산 시간: 0.0104초
속도 개선: 11.0배
