# 최신 표준: Generator 객체 사용법 (추천)

In [2]:
import numpy as np

# 1. 최신 표준 Generator 생성
rng = np.random.default_rng()
print(rng)

Generator(PCG64)


## rng.integers(low, high, size): 정수 무작위 추출

In [3]:
# 1 이상 46 미만(1~45)의 숫자 중 6개를 1차원 배열로 추출
lotto = rng.integers(1, 46, size=6)
print(lotto)  # 예: [12 45  3 24 18  7]

# 0 이상 10 미만의 정수로 채워진 2행 3열짜리 배열 생성
matrix_int = rng.integers(0, 10, size=(2, 3))
print(matrix_int)

[26 12 13 25 25 31]
[[8 6 0]
 [4 9 8]]


# rng.random(size): 0.0 이상 1.0 미만의 실수 추출

In [4]:
# 0.0 ~ 1.0 사이의 실수로 채워진 3행 2열 배열 생성
matrix_float = rng.random((3, 2))
print(matrix_float)

[[0.47420054 0.31915868]
 [0.50375711 0.96695026]
 [0.9937471  0.82766762]]


In [ ]:
# rng.choice(a, size, replace): 샘플 추출 (복원/비복원)

In [11]:
items = ['Apple', 'Banana', 'Orange', 'Grape']

# 중복을 허용하여 2개 선택 (기본값: replace=True)
print(rng.choice(items, size=2))

# 중복 없이 3개 선택 (비복원 추출)
print(rng.choice(items, size=3, replace=False))

['Orange' 'Orange']
['Banana' 'Apple' 'Grape']


In [ ]:
# rng.shuffle(x)/rng.permutation(x): 무작위 셔플

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.shuffle(arr)
print("원본:", arr)       # 원본이 변경
print("셔플본:", shuffled) # 반환값 없음(None)

원본: [1 2 3 5 4]
셔플본: None


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.permutation(arr)
print("원본:", arr)       # [1, 2, 3, 4, 5] 그대로 유지
print("셔플본:", shuffled) # 무작위 뒤섞인 배열

원본: [1 2 3 4 5]
셔플본: [2 4 5 3 1]


# 확률 분포 기반 난수 생성 (통계·머신러닝 필수)

In [ ]:
## rng.normal(loc, scale, size): 정규 분포 (Gaussian)

In [17]:
# 평균 0, 표준편차 1인 표준정규분포를 따르는 데이터 10,000개 생성
normal_data = rng.normal(loc=0.0, scale=1.0, size=10000)
print(normal_data)

[ 0.17902561  0.79317904  0.68634504 ...  0.8086756  -0.6027974
 -0.09472861]


In [ ]:
## rng.uniform(low, high, size): 균등 분포 (Uniform)

In [18]:
# 10.0부터 20.0 사이에서 균등한 확률로 5개 추출
uniform_data = rng.uniform(10.0, 20.0, size=5)
print(uniform_data)

[17.74966319 15.19821511 12.46971501 14.57325436 17.02784182]
