In [1]:
# 데이터 탐색 및 준비
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs, make_classification, make_regression

# 변환(정규화, 표준화)
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# 축소
from sklearn.decomposition import PCA
# 분리(train, test)
from sklearn.model_selection import train_test_split

In [2]:
# 분류 데이터 생성
# X: 독립(입력)변수
# y: 종속(출력)변수
X, y = make_classification(n_samples=100, n_features=5, random_state=42)
print(X)
print(y)

[[-0.43066755  0.67287309 -0.72427983 -0.53963044 -0.65160035]
 [ 0.21164583 -0.84389686  0.53479393  0.82584805  0.68195297]
 [ 1.09267506  0.40910605  1.10009583 -0.94275087 -0.98150865]
 [ 1.51990078 -0.77336118  1.99805321  0.15513175 -0.3853136 ]
 [-0.45390127 -2.18347304  0.24472415  2.59123946 -0.48423407]
 [-1.46361184  0.37531604 -1.79532002  0.25415746 -1.24778318]
 [ 0.88948365  0.80742726  0.73019848 -1.28568005  0.13074058]
 [-1.11327862  1.89033108 -1.92487377 -1.5598485   0.18645431]
 [ 0.63174629 -0.88541844  1.02703224  0.68057323  0.54709738]
 [-0.88602706 -0.83311649 -0.7173148   1.31217492  0.44381943]
 [ 0.56372286 -1.47487037  1.15509316  1.35536951 -0.2176812 ]
 [-1.02754411 -0.32929388 -1.05383855  0.82600732 -0.05952536]
 [ 0.19375402 -0.96314239  0.55600276  0.96423311 -0.20219265]
 [-0.05396947  0.15985512 -0.11708689 -0.15013844  0.82541635]
 [ 0.96335953  0.65992405  0.86561977 -1.15806823  0.46210347]
 [-1.09939128 -0.47936995 -1.08324727  1.02255619 -0.92

In [3]:
X.shape

(100, 5)

In [4]:
df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
df

,feature_1,feature_2,feature_3,feature_4,feature_5
0,-0.430668,0.672873,-0.724280,-0.539630,-0.651600
1,0.211646,-0.843897,0.534794,0.825848,0.681953
2,1.092675,0.409106,1.100096,-0.942751,-0.981509
3,1.519901,-0.773361,1.998053,0.155132,-0.385314
4,-0.453901,-2.183473,0.244724,2.591239,-0.484234
...,...,...,...,...,...
95,0.735948,1.203166,0.417673,-1.648321,-0.151785
96,0.846092,-1.140526,1.359706,0.861991,0.629629
97,-0.844677,1.643195,-1.533275,-1.411759,-1.612716
98,-1.282744,0.120370,-1.500776,0.450590,2.122156


In [5]:
df['target'] = y
df

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0
1,0.211646,-0.843897,0.534794,0.825848,0.681953,1
2,1.092675,0.409106,1.100096,-0.942751,-0.981509,0
3,1.519901,-0.773361,1.998053,0.155132,-0.385314,0
4,-0.453901,-2.183473,0.244724,2.591239,-0.484234,1
...,...,...,...,...,...,...
95,0.735948,1.203166,0.417673,-1.648321,-0.151785,0
96,0.846092,-1.140526,1.359706,0.861991,0.629629,1
97,-0.844677,1.643195,-1.533275,-1.411759,-1.612716,0
98,-1.282744,0.120370,-1.500776,0.450590,2.122156,1


In [6]:
# 분류 데이터 생성 -> 결측치 데이터 추가
def create_classification_data():
    X, y = make_classification(n_samples=100, n_features=5, random_state=42)
    df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
    df['target'] = y
    
    # feature_1에 결측치를 추가 (10% 비율로)
    # replace=False: 중복 없이
    missing_indices = np.random.choice(df.index, size=int(len(df) * 0.1), replace=False)
    df.loc[missing_indices, 'feature_1'] = np.nan
    
    return df

In [7]:
create_classification_data()

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0
1,0.211646,-0.843897,0.534794,0.825848,0.681953,1
2,1.092675,0.409106,1.100096,-0.942751,-0.981509,0
3,1.519901,-0.773361,1.998053,0.155132,-0.385314,0
4,-0.453901,-2.183473,0.244724,2.591239,-0.484234,1
...,...,...,...,...,...,...
95,0.735948,1.203166,0.417673,-1.648321,-0.151785,0
96,0.846092,-1.140526,1.359706,0.861991,0.629629,1
97,-0.844677,1.643195,-1.533275,-1.411759,-1.612716,0
98,-1.282744,0.120370,-1.500776,0.450590,2.122156,1


In [8]:
X, y = make_regression(n_samples=100, n_features=5, noise=0.1, random_state=42)
print(X)
print(y)

[[ 0.97511973 -0.67716171 -0.01224677 -0.89725437  0.07580456]
 [ 0.08187414 -0.48536355  0.75896922 -0.77282521 -0.23681861]
 [-1.4123037  -0.90802408 -0.56228753 -1.01283112  0.31424733]
 [-0.64511975  0.36163603  1.35624003 -0.07201012  1.0035329 ]
 [-0.62269952  0.28099187 -1.9520878  -0.1517851   0.58831721]
 [-0.45006547  0.04698059 -1.59442766 -0.59937502  0.0052437 ]
 [ 0.77463405  0.44381943 -0.48423407  1.26691115 -0.70766947]
 [ 0.35701549  0.8496021  -0.20812225 -0.49300093 -0.58936476]
 [-1.3044695  -0.08912004  0.38406545 -0.03269475 -2.0674421 ]
 [ 0.17318093 -1.24573878 -0.44651495  0.85639879  0.21409374]
 [ 0.29698467  0.52194157  0.78182287 -1.23695071 -1.32045661]
 [-1.72491783 -1.91328024 -0.46341769 -0.46572975  0.24196227]
 [-1.98756891  0.09176078  0.8219025   0.08704707 -0.29900735]
 [-0.0555477  -1.70338244  0.07409478  1.62861555 -1.38010146]
 [ 0.65655361 -1.1913035  -0.71435142  1.86577451  0.47383292]
 [-0.01901621 -0.15993853  0.31090757  1.47535622  0.85

In [9]:
df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
df['target'] = y
df

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,0.975120,-0.677162,-0.012247,-0.897254,0.075805,-57.195760
1,0.081874,-0.485364,0.758969,-0.772825,-0.236819,-46.546477
2,-1.412304,-0.908024,-0.562288,-1.012831,0.314247,-258.133440
3,-0.645120,0.361636,1.356240,-0.072010,1.003533,115.850751
4,-0.622700,0.280992,-1.952088,-0.151785,0.588317,-123.767712
...,...,...,...,...,...,...
95,-1.514847,-0.846794,0.714000,0.473238,-0.072829,-104.690611
96,-0.773010,0.097676,-0.401220,0.224092,0.012592,-49.838794
97,1.031000,0.611676,0.324084,-0.385082,-0.676922,97.685689
98,-0.234587,0.005113,-1.463515,0.296120,0.261055,-81.877244


In [10]:
for column in df.columns[:-1]:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    # 하한선
    lower_bound = Q1 - 1.5 * IQR
    # 상한선
    upper_bound = Q3 + 1.5 * IQR

    print('Q1: ', Q1)
    print('Q3: ', Q3)
    print('IQR: ', IQR)
    print('lower_bound: ', lower_bound)
    print('upper_bound: ', upper_bound)

Q1:  -0.757046224351652
Q3:  0.6481703643473181
IQR:  1.4052165886989703
lower_bound:  -2.8648711074001074
upper_bound:  2.7559952473957736
Q1:  -0.5362881870446912
Q3:  0.6679290024283391
IQR:  1.2042171894730302
lower_bound:  -2.3426139712542366
upper_bound:  2.474254786637885
Q1:  -0.734896607926991
Q3:  0.5242373966020439
IQR:  1.259134004529035
lower_bound:  -2.623597614720543
upper_bound:  2.4129384033955965
Q1:  -0.6781359668162878
Q3:  0.8306448185767356
IQR:  1.5087807853930233
lower_bound:  -2.9413071449058226
upper_bound:  3.0938159966662706
Q1:  -0.7003074044637773
Q3:  0.5324187648053007
IQR:  1.2327261692690779
lower_bound:  -2.549396658367394
upper_bound:  2.3815080187089173


In [11]:
# 회귀 데이터 생성 -> 이상치 데이터 추가
def create_regression_data():
    X, y = make_regression(n_samples=100, n_features=5, noise=0.1, random_state=42)
    df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
    df['target'] = y

    # IQR(Interquartile Range): 이상치 포함여부 판단
    for column in df.columns[:-1]:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1

        # 하한선
        lower_bound = Q1 - 1.5 * IQR
        # 상한선
        upper_bound = Q3 + 1.5 * IQR

        # 이상치를 추가할 인덱스를 랜덤하게 선택
        outlier_indices = np.random.choice(df.index, size=5, replace=False)
        for idx in outlier_indices:
            # at[행, 열]
            df.at[idx, column] = np.random.uniform(upper_bound + 1, upper_bound + 10)

    return df

In [12]:
create_regression_data()

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,0.975120,-0.677162,-0.012247,-0.897254,0.075805,-57.195760
1,0.081874,-0.485364,0.758969,-0.772825,-0.236819,-46.546477
2,-1.412304,-0.908024,7.625484,4.708727,0.314247,-258.133440
3,-0.645120,0.361636,1.356240,-0.072010,1.003533,115.850751
4,-0.622700,0.280992,-1.952088,-0.151785,0.588317,-123.767712
...,...,...,...,...,...,...
95,-1.514847,-0.846794,0.714000,0.473238,-0.072829,-104.690611
96,6.707093,0.097676,-0.401220,0.224092,0.012592,-49.838794
97,1.031000,0.611676,0.324084,-0.385082,-0.676922,97.685689
98,-0.234587,0.005113,-1.463515,0.296120,0.261055,-81.877244


In [13]:
# 군집 데이터 생성 함수
def create_blobs_data():
    X, y = make_blobs(n_samples=100, n_features=5, centers=3, random_state=42)
    df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
    df['target'] = y
    
    return df

In [14]:
create_blobs_data()

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,-3.002630,9.937449,6.346484,2.846759,-6.870483,0
1,-5.970371,-9.040785,7.384420,2.669463,4.287546,1
2,-2.290559,9.896047,3.630793,0.389875,-6.105927,0
3,-3.463695,8.263107,3.509451,2.743147,-5.611238,0
4,-1.888649,8.853349,4.251614,1.087657,-7.236372,0
...,...,...,...,...,...,...
95,-5.813911,-9.797336,8.705528,2.927422,3.557547,1
96,-2.334365,7.797431,5.689226,3.298275,-6.145126,0
97,-3.138673,9.612007,7.199367,2.367403,-6.757408,0
98,-1.927075,9.902035,5.534211,2.728167,-7.086793,0


In [15]:
# Generate datasets for each problem type
classification_df = create_classification_data()
regression_df = create_regression_data()
blobs_df = create_blobs_data()

In [16]:
print('=== Classification Generated Datasets ===')
print(classification_df.head())
print('\n=== regression Generated Datasets ===')
print(regression_df.head())
print('\n=== blobs Generated Datasets ===')
print(blobs_df.head())

=== Classification Generated Datasets ===
   feature_1  feature_2  feature_3  feature_4  feature_5  target
0  -0.430668   0.672873  -0.724280  -0.539630  -0.651600       0
1   0.211646  -0.843897   0.534794   0.825848   0.681953       1
2   1.092675   0.409106   1.100096  -0.942751  -0.981509       0
3   1.519901  -0.773361   1.998053   0.155132  -0.385314       0
4  -0.453901  -2.183473   0.244724   2.591239  -0.484234       1

=== regression Generated Datasets ===
   feature_1  feature_2  feature_3  feature_4  feature_5      target
0   0.975120  -0.677162  -0.012247  -0.897254   0.075805  -57.195760
1   0.081874  -0.485364   0.758969  -0.772825  -0.236819  -46.546477
2  -1.412304  -0.908024  -0.562288  -1.012831   0.314247 -258.133440
3  -0.645120   0.361636   1.356240  -0.072010   1.003533  115.850751
4  -0.622700   0.280992  -1.952088  -0.151785   0.588317 -123.767712

=== blobs Generated Datasets ===
   feature_1  feature_2  feature_3  feature_4  feature_5  target
0  -3.002630   9

## 데이터 정제
### 1. 결측치 제거

In [17]:
# 결측치 확인
classification_df.isna()

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
95,False,False,False,False,False,False
96,False,False,False,False,False,False
97,False,False,False,False,False,False
98,False,False,False,False,False,False


In [18]:
print('[전처리 전] 결측치 수:', classification_df.isna().sum())

[전처리 전] 결측치 수: feature_1    10
feature_2     0
feature_3     0
feature_4     0
feature_5     0
target        0
dtype: int64


In [19]:
print('[전처리 전] 결측치 수:', classification_df.isna().sum().sum())

[전처리 전] 결측치 수: 10


In [20]:
# 결측치를 feature_1의 평균값으로 변경
classification_df['feature_1'] = classification_df['feature_1'].fillna(classification_df['feature_1'].mean())
print('[전처리 후] 결측치 수:', classification_df.isna().sum().sum())

[전처리 후] 결측치 수: 0


### 2. 이상치 제거

In [21]:
print('이상치 처리 전 결측치 수:', regression_df['feature_3'].isna().sum())

이상치 처리 전 결측치 수: 0


In [22]:
# IQR
Q1 = regression_df['feature_3'].quantile(0.25)
Q3 = regression_df['feature_3'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 이상치를 결측치로 변환
regression_df.loc[(regression_df['feature_3'] < lower_bound) | (regression_df['feature_3'] > upper_bound), 'feature_3'] = None

print('이상치 처리 후 결측치 수:', regression_df['feature_3'].isna().sum())

이상치 처리 후 결측치 수: 5


In [23]:
regression_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   feature_1  100 non-null    float64
 1   feature_2  100 non-null    float64
 2   feature_3  95 non-null     float64
 3   feature_4  100 non-null    float64
 4   feature_5  100 non-null    float64
 5   target     100 non-null    float64
dtypes: float64(6)
memory usage: 4.8 KB


In [24]:
regression_df.dropna(subset=['feature_3'], inplace=True)
print('결측치 삭제:', regression_df['feature_3'].isna().sum())

결측치 삭제: 0


In [25]:
regression_df.info()

<class 'pandas.DataFrame'>
Index: 95 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   feature_1  95 non-null     float64
 1   feature_2  95 non-null     float64
 2   feature_3  95 non-null     float64
 3   feature_4  95 non-null     float64
 4   feature_5  95 non-null     float64
 5   target     95 non-null     float64
dtypes: float64(6)
memory usage: 5.2 KB


## 데이터 통합

In [26]:
# 수평 결합
# axis=1: 결합의 축을 열(Column) 방향
pd.concat([classification_df, regression_df], axis=1)

,feature_1,feature_2,feature_3,feature_4,feature_5,target,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,0.975120,-0.677162,-0.012247,-0.897254,0.075805,-57.195760
1,0.211646,-0.843897,0.534794,0.825848,0.681953,1,0.081874,-0.485364,0.758969,-0.772825,-0.236819,-46.546477
2,1.092675,0.409106,1.100096,-0.942751,-0.981509,0,-1.412304,-0.908024,-0.562288,-1.012831,0.314247,-258.133440
3,1.519901,-0.773361,1.998053,0.155132,-0.385314,0,-0.645120,0.361636,1.356240,-0.072010,1.003533,115.850751
4,-0.453901,-2.183473,0.244724,2.591239,-0.484234,1,-0.622700,0.280992,-1.952088,-0.151785,0.588317,-123.767712
...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.735948,1.203166,0.417673,-1.648321,-0.151785,0,-1.514847,-0.846794,0.714000,0.473238,4.025765,-104.690611
96,0.846092,-1.140526,1.359706,0.861991,0.629629,1,-0.773010,0.097676,-0.401220,0.224092,0.012592,-49.838794
97,-0.844677,1.643195,-1.533275,-1.411759,-1.612716,0,1.031000,0.611676,0.324084,-0.385082,-0.676922,97.685689
98,-1.282744,0.120370,-1.500776,0.450590,2.122156,1,-0.234587,0.005113,-1.463515,0.296120,0.261055,-81.877244


In [27]:
# 병합(조인)
# on='target': 병합 기준 열
pd.merge(classification_df, blobs_df, on='target', how='inner')

,feature_1_x,feature_2_x,feature_3_x,feature_4_x,feature_5_x,target,feature_1_y,feature_2_y,feature_3_y,feature_4_y,feature_5_y
0,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-3.002630,9.937449,6.346484,2.846759,-6.870483
1,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-2.290559,9.896047,3.630793,0.389875,-6.105927
2,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-3.463695,8.263107,3.509451,2.743147,-5.611238
3,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-1.888649,8.853349,4.251614,1.087657,-7.236372
4,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-2.768226,8.439577,4.218381,2.312991,-6.887007
...,...,...,...,...,...,...,...,...,...,...,...
3345,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-7.117502,-6.966322,7.304081,1.089709,2.866509
3346,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-6.676287,-8.279219,8.196065,3.176655,3.684070
3347,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-5.902930,-8.796348,7.186251,1.898168,4.901792
3348,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-5.813911,-9.797336,8.705528,2.927422,3.557547


## 데이터 탐색(EDA)

In [28]:
# 그룹별 평균
classification_df.groupby('target')[['feature_1', 'feature_2', 'feature_3']].mean()

,feature_1,feature_2,feature_3
target,,,
0,0.070616,1.006369,-0.181439
1,-0.235811,-0.929705,0.083742


## 데이터 변환

In [29]:
blobs_df

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,-3.002630,9.937449,6.346484,2.846759,-6.870483,0
1,-5.970371,-9.040785,7.384420,2.669463,4.287546,1
2,-2.290559,9.896047,3.630793,0.389875,-6.105927,0
3,-3.463695,8.263107,3.509451,2.743147,-5.611238,0
4,-1.888649,8.853349,4.251614,1.087657,-7.236372,0
...,...,...,...,...,...,...
95,-5.813911,-9.797336,8.705528,2.927422,3.557547,1
96,-2.334365,7.797431,5.689226,3.298275,-6.145126,0
97,-3.138673,9.612007,7.199367,2.367403,-6.757408,0
98,-1.927075,9.902035,5.534211,2.728167,-7.086793,0


In [30]:
# 원-핫 인코딩
# prefix: 기본값은 열이름_순번
pd.get_dummies(blobs_df, columns=['target'], prefix='t')

,feature_1,feature_2,feature_3,feature_4,feature_5,t_0,t_1,t_2
0,-3.002630,9.937449,6.346484,2.846759,-6.870483,True,False,False
1,-5.970371,-9.040785,7.384420,2.669463,4.287546,False,True,False
2,-2.290559,9.896047,3.630793,0.389875,-6.105927,True,False,False
3,-3.463695,8.263107,3.509451,2.743147,-5.611238,True,False,False
4,-1.888649,8.853349,4.251614,1.087657,-7.236372,True,False,False
...,...,...,...,...,...,...,...,...
95,-5.813911,-9.797336,8.705528,2.927422,3.557547,False,True,False
96,-2.334365,7.797431,5.689226,3.298275,-6.145126,True,False,False
97,-3.138673,9.612007,7.199367,2.367403,-6.757408,True,False,False
98,-1.927075,9.902035,5.534211,2.728167,-7.086793,True,False,False


In [32]:
# feature_6 = feature_1 + feature_2
blobs_df['feature_6'] = blobs_df['feature_1'] + blobs_df['feature_2']

# feature_7 = (feature_3 + feature_4 + feature_5) / 3
blobs_df['feature_7'] = blobs_df[['feature_3', 'feature_4', 'feature_5']].mean(axis=1)

blobs_df

,feature_1,feature_2,feature_3,feature_4,feature_5,target,feature_6,feature_7
0,-3.002630,9.937449,6.346484,2.846759,-6.870483,0,6.934819,0.774253
1,-5.970371,-9.040785,7.384420,2.669463,4.287546,1,-15.011157,4.780476
2,-2.290559,9.896047,3.630793,0.389875,-6.105927,0,7.605488,-0.695086
3,-3.463695,8.263107,3.509451,2.743147,-5.611238,0,4.799412,0.213787
4,-1.888649,8.853349,4.251614,1.087657,-7.236372,0,6.964699,-0.632367
...,...,...,...,...,...,...,...,...
95,-5.813911,-9.797336,8.705528,2.927422,3.557547,1,-15.611247,5.063499
96,-2.334365,7.797431,5.689226,3.298275,-6.145126,0,5.463067,0.947458
97,-3.138673,9.612007,7.199367,2.367403,-6.757408,0,6.473334,0.936454
98,-1.927075,9.902035,5.534211,2.728167,-7.086793,0,7.974960,0.391862


In [33]:
# 정규화: 0~1 사이값으로 변환
scaler = MinMaxScaler()
regression_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']] = scaler.fit_transform(regression_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']])

regression_df

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,0.337543,0.087372,0.454642,0.095402,0.258324,-57.195760
1,0.253671,0.100928,0.635392,0.103853,0.233978,-46.546477
2,0.113374,0.071054,0.325728,0.087552,0.276894,-258.133440
3,0.185409,0.160796,0.775375,0.151451,0.330573,115.850751
4,0.187514,0.155096,0.000000,0.146033,0.298237,-123.767712
...,...,...,...,...,...,...
95,0.103745,0.075382,0.624853,0.188483,0.565936,-104.690611
96,0.173401,0.142139,0.363478,0.171561,0.253402,-49.838794
97,0.342790,0.178470,0.533468,0.130188,0.199704,97.685689
98,0.223956,0.135596,0.114507,0.176453,0.272751,-81.877244


In [36]:
# 표준화: 평균 0, 표준편차 1, 표준정규분포
scaler = StandardScaler()
classification_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']] = scaler.fit_transform(classification_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']])

classification_df

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,-0.417184,0.500431,-0.551841,-0.388604,-0.679322,0
1,0.352669,-0.695771,0.476848,0.647953,0.651310,1
2,1.408639,0.292411,0.938711,-0.694620,-1.008507,0
3,1.920696,-0.640143,1.672360,0.138801,-0.413618,0
4,-0.445031,-1.752229,0.239855,1.988092,-0.512322,1
...,...,...,...,...,...,...
95,0.981078,0.918648,0.381157,-1.230230,-0.180601,0
96,1.113093,-0.929708,1.150817,0.675390,0.599101,1
97,-0.913400,1.265677,-1.212807,-1.050652,-1.638332,0
98,-1.438451,0.064700,-1.186254,0.363089,2.088358,1


## 데이터 축소

In [37]:
# PCA(주성분 분석)
pca = PCA(n_components=3)
principal_components = pca.fit_transform(regression_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']])

principal_df = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2', 'PC3'])

principal_df

,PC1,PC2,PC3
0,-0.003711,-0.110848,0.004589
1,0.190682,-0.105595,-0.019945
2,-0.052895,0.033293,-0.201527
3,0.338315,-0.010324,0.006423
4,-0.392198,0.108551,-0.191479
...,...,...,...
90,0.236814,0.198290,-0.011547
91,-0.044294,0.042818,-0.112054
92,0.056989,-0.128649,0.026225
93,-0.293304,0.074039,-0.125202


## 데이터 분할

In [38]:
classification_df

,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,-0.417184,0.500431,-0.551841,-0.388604,-0.679322,0
1,0.352669,-0.695771,0.476848,0.647953,0.651310,1
2,1.408639,0.292411,0.938711,-0.694620,-1.008507,0
3,1.920696,-0.640143,1.672360,0.138801,-0.413618,0
4,-0.445031,-1.752229,0.239855,1.988092,-0.512322,1
...,...,...,...,...,...,...
95,0.981078,0.918648,0.381157,-1.230230,-0.180601,0
96,1.113093,-0.929708,1.150817,0.675390,0.599101,1
97,-0.913400,1.265677,-1.212807,-1.050652,-1.638332,0
98,-1.438451,0.064700,-1.186254,0.363089,2.088358,1


In [39]:
X = classification_df.drop(columns=['target'])
y = classification_df['target']

# 훈련 세트(Train Set)와 테스트 세트(Test Set) 두 개로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(80, 5) (20, 5) (80,) (20,)
